services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      # Variables para la conexión a MySQL
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=remoto
      - DATABASE_PASSWORD=Remoto123!
      - DATABASE_NAME=ERP
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=ERP
      - MYSQL_USER=remoto
      - MYSQL_PASSWORD=Remoto123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Monta la carpeta con el script de inicialización
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
